name: Main workflow

on:
  [push]

permissions:
  actions: write
  contents: read

jobs:
  test-julia:
    name: Test julia ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Julia
        uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}

      - uses: julia-actions/cache@v2

      - uses: julia-actions/julia-buildpkg@latest
        with:
          project: .

      - name: set cores number
        run: echo "JULIA_NUM_THREADS=2" >> $GITHUB_ENV

      - name: Set CPU backend
        run: echo "[Flux]" > LocalPreferences.toml && echo "gpu_backend = \"CPU\"" >> LocalPreferences.toml

      - name: Run Julia package tests
        uses: julia-actions/julia-runtest@latest
        with:
          project: .

  build-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/expcoder-dev
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  test-arc-dummy:
    name: Test ARC with dummy guiding model ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Julia
        uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}

      - uses: julia-actions/cache@v2

      - uses: julia-actions/julia-buildpkg@latest
        with:
          project: .

      - name: set cores number
        run: echo "JULIA_NUM_THREADS=2" >> $GITHUB_ENV

      - name: Set CPU backend
        run: echo "[Flux]" > LocalPreferences.toml && echo "gpu_backend = \"CPU\"" >> LocalPreferences.toml

      - name: Run solver
        run: julia --project=. scripts/main.jl -c 2

  test-arc-nn:
    name: Test ARC with neural guiding model ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Julia
        uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}

      - uses: julia-actions/cache@v2

      - uses: julia-actions/julia-buildpkg@latest
        with:
          project: .

      - name: set cores number
        run: echo "JULIA_NUM_THREADS=2" >> $GITHUB_ENV

      - name: Set CPU backend
        run: echo "[Flux]" > LocalPreferences.toml && echo "gpu_backend = \"CPU\"" >> LocalPreferences.toml

      - name: Run solver
        run: julia --project=. scripts/main.jl -c 2 -m nn
