name: Main workflow

on:
  [push]

permissions:
  actions: write
  contents: read

jobs:
  test-julia:
    name: Test julia ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Julia
        uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}

      - uses: julia-actions/cache@v2

      - uses: julia-actions/julia-buildpkg@latest
        with:
          project: .

      - name: set cores number
        run: echo "JULIA_NUM_THREADS=2" >> $GITHUB_ENV

      - name: Setup redis
        uses: zhulik/redis-action@1.1.0
        with:
          redis version: '5'

      - name: Run Julia package tests
        uses: julia-actions/julia-runtest@latest
        with:
          project: .

  build-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ghcr.io/${{ github.repository_owner }}/expcoder-dev

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
